name: Gatsby Publish

on:
  push:
    branches:
      - gatsby

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2.2.1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-branch: main
